name: CI-CD
on: 
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Obtendo o código
      uses: actions/checkout@v4.1.5
    - name: Autenticação no Docker Hub
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build da Imagem Docker
      uses: docker/build-push-action@v5.3.0
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: | 
          rodrigo2186/aula-primeira-pipeline:v${{ github.run_number }} 
          rodrigo2186/aula-primeira-pipeline:latest 
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps: 
    - name: Obtendo o código
      uses: actions/checkout@v4.1.5
    - name: Authenticate to Google
      uses: "google-github-actions/auth@v2"
      with:
        credentials_json: "${{ secrets.GCP_SERVICEACCOUNT_KEY }}"
    - name: Setup GCLOUD   
      uses: "google-github-actions/setup-gcloud@v2"
      with: 
        install_components: "gke-gcloud-auth-plugin"
    - name: Authenticate to GKE cluster
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: cluster-1
        location: us-central1      
    - name: Configuração de contexto do Kubernetes
      uses: azure/k8s-set-context@v4.0.0
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.K8S_CONFIG }}
    - name: Execução do Manifesto
      uses: Azure/k8s-deploy@v5
      with:
        manifests: |
          ./k8s/deployment.yaml
        images: |
          rodrigo2186/aula-primeira-pipeline:v${{ github.run_number }}
